version: '3'

services:
  db:
    image: mariadb:10.7
    container_name: db
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
    volumes:
      - db:/var/lib/mysql
    ports:
      - 3306:3306
    
  webserver:
    image: nginx:1.22.0
    container_name: webserver
    restart: always
    volumes:
      - ./logs/nginx/:/var/log/nginx/
      - ./config/nginx/sites-enabled/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./site/:/var/www/app/
    ports:
      - 80:80
      - 443:443

  php-fpm:
    container_name: php-fpm
    build: ./php
    restart: always
    volumes:
      - ./site/:/var/www/app/
    ports:
      - 9000:9000

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  db: