name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Setup key
      - run: set -eu
      - run: mkdir "$HOME/.ssh"
      - run: echo "${{ secrets.key }}" > "$HOME/.ssh/key"
      - run: chmod 600 "$HOME/.ssh/key"
      # Build
#      - run: npm ci
#      - run: npm run build
      # Deploy
      - run: cd site && rsync -e "ssh -p 20022 -i $HOME/.ssh/key -o StrictHostKeyChecking=no" --archive --compress --delete . root@185.65.246.107:/home/ppp-industry/sites/pavluk-app.ppp-industry.com





#name: deploy
#on:
#  push:
#    branches:
#      - main
#      - master
#  schedule:
#    - cron: '0 0 * * *' # Everyday at 12am
#jobs:
#  build-and-deploy:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-node@v1
#
#      - run: npm install
#      - run: npm run build
#
#      - name: Install SSH Key
#        uses: shimataro/ssh-key-action@v2
#        with:
#          key: ${{ secrets.SSH_PRIVATE_KEY }}
#          known_hosts: unnecessary
#
#      - name: Adding Known Hosts
#        run: ssh-keyscan -p ${{ secrets.SSH_PORT}} -H ${{ secrets.SSH_HOST }}  >> ~/.ssh/known_hosts
#
#      - name: Deploy with rsync
#        run: rsync -avz -e "ssh -p ${{ secrets.SSH_PORT }}" ./dist/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/zellwk.com/
#
#      - name: Restart Node Server
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.SSH_HOST }}
#          username: ${{ secrets.SSH_USER }}
#          key: ${{ secrets.SSH_PRIVATE_KEY }}
#          port: ${{ secrets.SSH_PORT }}
#          script: |
#            cd /var/www/zellwk.com
#            git fetch origin master
#            git reset --hard FETCH_HEAD
#            git clean -d -f --exclude secrets
#            npm install --production
#            chown $(whoami) . # PM2 doesn't recognize root user from Github Actions
#            npm run restart